### ISSUE TITLE
Netz appears as 11.7 on wrong team

### ISSUE THREAD

**Issue by Daniel-Webster** [solawk/wtlineup#1]
Hey think I might have found a bug the Netz f16 for Isreal shows up on the wrong team and at the wrong br (should be 12.0 I think)

Seems there are some other mismatches in my screenshot with wrong team.

![Screenshot_20240515_200332_Chrome](https://github.com/solawk/wtlineup/assets/61659559/4e2f6e36-3052-4f61-bafe-f701ec7922ff)

**Comment by solawk** [comment]
Hello!
Fixed its BR to indeed be 12.0.
In the Enduring Confrontation mode nations above the table don't display the actual opposing sides, since they can vary from battle to battle. Aircraft being in the left or right column of the table doesn't signify anything, as it's made merely to display more planes at a time on the screen.
Please use the report button in the lower-right corner to message about the BR mismatches or similar problems, thank you
